-- Easy
-- 1. Retrieve all albums from the Album table.
SELECT title FROM album;

-- 2. List all artists in alphabetical order.
SELECT name FROM artist
ORDER BY name;

-- 3. Find the first and last names of all customers.
SELECT CONCAT(first_name, ' ', last_name) FROM customer;

-- 4. Get the names of all tracks from the Track table.
SELECT name FROM track;

-- 5. List all invoices from the year 2010.
SELECT * FROM invoice
WHERE EXTRACT(YEAR FROM invoice_date) = 2021;

-- 6. Find the names of all playlists.
SELECT name FROM playlist;

-- 7. Count the number of employees in the company.
SELECT DISTINCT COUNT(*) FROM employee;

-- 8. List the titles of all albums released by the artist "AC/DC."
SELECT name, title FROM artist ar
JOIN album al
ON ar.artist_id = al.artist_id
WHERE name = 'AC/DC';

-- 9. Retrieve the names of all unique genres in the Genre table.
SELECT DISTINCT name FROM genre;

-- 10. Show all customers who live in the USA.
SELECT CONCAT(first_name, ' ', last_name), country FROM customer
WHERE country = 'USA';

-- Intermediate
-- 11. Retrieve the total number of tracks in each playlist.
SELECT p.name, COUNT(pt.track_id) FROM playlist p
JOIN playlist_track pt
ON p.playlist_id = pt.playlist_id
GROUP BY p.name
ORDER BY count DESC;
-- 12. Get the names of all customers who have made more than 5 purchases.
SELECT CONCAT(c.first_name, ' ', c.last_name), COUNT(invoice_id) FROM invoice i
JOIN customer c
ON c.customer_id = i.customer_id
GROUP BY c.customer_id
HAVING COUNT(invoice_id) > 5;

-- 13. List the top 5 selling tracks in the database.
SELECT track_id, unit_price, quantity FROM invoice_line
ORDER BY quantity DESC
LIMIT 5;

-- 14. Find the total sales revenue generated by each employee.
SELECT * FROM invoice;

-- 15. Get the average invoice total per customer.
SELECT customer_id, ROUND(AVG(unit_price * quantity), 2) AS avg_total FROM invoice i
JOIN invoice_line il
ON i.invoice_id = il.invoice_id
GROUP BY customer_id
ORDER BY avg_total DESC;

-- 16. List all tracks along with their respective genre names.
SELECT t.name, g.name FROM track t
JOIN genre g
ON t.genre_id = g.genre_id;

-- 17. Retrieve the total number of tracks per album.
SELECT a.title, COUNT(t.name) FROM album a
JOIN track t
ON a.album_id = t.album_id
GROUP BY a.title
ORDER BY a.title;

-- 18. Get a list of all customers and their total purchases in descending order.
SELECT CONCAT(first_name, ' ', last_name) AS name, COUNT(invoice_id) FROM customer c
JOIN invoice i 
ON c.customer_id = i.customer_id
GROUP BY name
ORDER BY count DESC;

-- 19. Find the total revenue for each country.
SELECT billing_country, SUM(total) AS total FROM invoice
GROUP BY billing_country
ORDER BY total DESC;

-- 20. Retrieve a list of employees who report to a specific manager.
SELECT reports_to AS manager, STRING_AGG((CONCAT(first_name, ' ', last_name)), ', ') AS employee_list  
FROM employee
GROUP BY manager;

-- Advanced
-- 21. Get the name and total sales amount for the top customer.
SELECT CONCAT(c.first_name, ' ', c.last_name) AS customer_name, SUM(i.total) AS total_sales
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 1;
-- 22. Find the track with the longest duration and its associated album and artist.
SELECT t.name AS track_name, a.title AS album_title, ar.name AS artist_name, t.milliseconds AS duration
FROM track t
JOIN album a ON t.album_id = a.album_id
JOIN artist ar ON a.artist_id = ar.artist_id
ORDER BY t.milliseconds DESC
LIMIT 1;
-- 23. Get the total revenue generated per genre.
SELECT g.name AS genre_name, SUM(il.unit_price * il.quantity) AS total_revenue
FROM genre g
JOIN track t ON g.genre_id = t.genre_id
JOIN invoice_line il ON t.track_id = il.track_id
JOIN invoice i ON il.invoice_id = i.invoice_id
GROUP BY g.name
ORDER BY total_revenue DESC;
-- 24. Retrieve a list of customers who have not made any purchases.
SELECT CONCAT(first_name, ' ', last_name) AS customer_name
FROM customer c
WHERE NOT EXISTS (
    SELECT 1 
    FROM invoice i 
    WHERE c.customer_id = i.customer_id
);
-- 25. Find all tracks that belong to more than one playlist.
SELECT t.name AS track_name, COUNT(pt.playlist_id) AS playlist_count
FROM track t
JOIN playlist_track pt ON t.track_id = pt.track_id
GROUP BY t.track_id
HAVING COUNT(pt.playlist_id) > 1;
-- 26. Calculate the total number of tracks sold for each media type.
SELECT mt.name AS media_type, SUM(il.quantity) AS total_tracks_sold
FROM media_type mt
JOIN track t ON mt.media_type_id = t.media_type_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY mt.name;
-- 27. List the names of all customers who have made purchases in more than one country.
SELECT CONCAT(c.first_name, ' ', c.last_name) AS customer_name
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY c.customer_id
HAVING COUNT(DISTINCT i.billing_country) > 1;
-- 28. Get the artist who has sold the most tracks and the total sales amount.
SELECT ar.name AS artist_name, SUM(il.quantity) AS total_tracks_sold
FROM artist ar
JOIN album a ON ar.artist_id = a.artist_id
JOIN track t ON a.album_id = t.album_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY ar.artist_id
ORDER BY total_tracks_sold DESC
LIMIT 1;
-- 29. List the albums that have no tracks associated with them.
SELECT a.title AS album_title
FROM album a
LEFT JOIN track t ON a.album_id = t.album_id
WHERE t.track_id IS NULL;
-- 30. Retrieve the names of all employees who have not supervised any other employees.
SELECT CONCAT(first_name, ' ', last_name) AS employee_name
FROM employee e
WHERE NOT EXISTS (
    SELECT 1
    FROM employee e2
    WHERE e2.reports_to = e.employee_id
);
